### ISSUE TITLE
Part 2.1: Extract Data Attributes

### ISSUE THREAD

**Issue by ykomal** [Egnite-git/ds-python-du-noelakkidas#5]

**Comment by noelakkidas** [comment]
[Articles on Economy in THE HINDU.xlsx](https://github.com/Egnite-git/ds-python-du-noelakkidas/files/7654256/Articles.on.Economy.in.THE.HINDU.xlsx)

**Comment by noelakkidas** [comment]
Dear mam,
I have uploaded the Jupyer Notebook file and excel sheet please go through it.
